export const GET_RESTAURANT_DATA_REQUEST='GET_RESTAURANT_DATA_REQUEST'
export const GET_RESTAURANT_DATA_SUCCESS='GET_RESTAURANT_DATA_SUCCESS'
export const GET_RESTAURANT_DATA_FAIL='GET_RESTAURANT_DATA_FAIL'


// Order Operations
export const CREATE_ORDER_RESTAURANT_REQUEST = 'CREATE_ORDER_RESTAURANT_REQUEST';
export const CREATE_ORDER_RESTAURANT_SUCCESS = 'CREATE_ORDER_RESTAURANT_SUCCESS';
export const CREATE_ORDER_RESTAURANT_FAIL = 'CREATE_ORDER_RESTAURANT_FAIL';

export const FETCH_ORDER_HISTORY_RESTAURANT_REQUEST = 'FETCH_ORDER_HISTORY_RESTAURANT_REQUEST';
export const FETCH_ORDER_HISTORY_RESTAURANT_SUCCESS = 'FETCH_ORDER_HISTORY_RESTAURANT_SUCCESS';
export const FETCH_ORDER_HISTORY_RESTAURANT_FAIL = 'FETCH_ORDER_HISTORY_RESTAURANT_FAIL';

export const UPDATE_ORDER_COLLECTOR_REQUEST = 'UPDATE_ORDER_COLLECTOR_REQUEST';
export const UPDATE_ORDER_COLLECTOR_SUCCESS = 'UPDATE_ORDER_COLLECTOR_SUCCESS';
export const UPDATE_ORDER_COLLECTOR_FAIL = 'UPDATE_ORDER_COLLECTOR_FAIL';

// Collector Operations
export const FETCH_COLLECTOR_DATA_REQUEST = 'FETCH_COLLECTOR_DATA_REQUEST';
export const FETCH_COLLECTOR_DATA_SUCCESS = 'FETCH_COLLECTOR_DATA_SUCCESS';
export const FETCH_COLLECTOR_DATA_FAIL = 'FETCH_COLLECTOR_DATA_FAIL';

export const FETCH_COLLECTOR_HISTORY_REQUEST = 'FETCH_COLLECTOR_HISTORY_REQUEST';
export const FETCH_COLLECTOR_HISTORY_SUCCESS = 'FETCH_COLLECTOR_HISTORY_SUCCESS';
export const FETCH_COLLECTOR_HISTORY_FAIL = 'FETCH_COLLECTOR_HISTORY_FAIL';

// ... (any other constants or actions needed)

// Example action creator for creating an order
// export const createOrderRestaurant = (orderData) => ({
//   type: CREATE_ORDER_RESTAURANT_REQUEST,
//   payload: orderData, // Replace with appropriate data based on your API/data structure
// });

export const CLEAR_ERROR='CLEAR_ERROR'